schemas/BaseElements.xsd

allowing zero bedrooms

---

schemas/HPXMLDataTypes.xsd

Add Enumeration "underside of rafters" for radiant barrier

---

schemas/BaseElements.xsd

allowing multiple ThirdPartyCertifications for WaterHeatingSystems

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #38 
What do you think of this @brandongallagher @GamalielL?
I still don't like the names, and am open to alternatives.

Adding VerticalSurroundings

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Enumerations:
- interior
- exterior
@brandongallagher
fixes #72

adding plug load location

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adding `Building/BuildingDetails/Systems/MechanicalVentilation/VentilationFan/ThirdPartyCertification`
with the following enumerations:
- Energy Star
- other
fixes #44

Adding VentilationFan third party enumeration

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Here's my straw man at a wind system.
- Do we need `RatedCapacity`? Isn't that covered by the other AWEA elements?
- I left off actual annual output because we're unlikely to ever get it and the point is to document the physical characteristics anyway.
Fixes #52 
@RebHudson

Wind System

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Air Filter Changes (MERV, date)

---

examples/bpi2101.xml
examples/upgrade.xml

These are the examples from the validator/viewer app at https://hpxml.nrel.gov
Fixes #35

Adding examples from validator app

---

schemas/BaseElements.xsd

This permits listing the fuels available at a site.

Adding FuelTypesAvailable

---

schemas/HPXMLDataTypes.xsd

Add VentilationFanType enum choices for balanced and cfis.

Additional vent fan types

---

schemas/BaseElements.xsd

Adds UniformEnergyFactor to WaterHeatingSystem.

UniformEnergyFactor

---

schemas/BaseElements.xsd

Note: FoundationWall/Thickness already exists.

Adds Slab/Thickness

---

schemas/BaseElements.xsd

Adds `ElectricityDemandKW` to `ModeledUsages`.
Fixes #117.

Adding ElectricityDemandKW

---

schemas/BaseElements.xsd

An input collected by DOE's Home Energy Score.
FYI @lirainer

Adds PV element for number of panels

---

schemas/BaseElements.xsd

Adds `Quantity` field for `CeilingFan` and `WaterFixture` elements.

Add Quantity field for CeilingFan/WaterFixture

---

schemas/BaseElements.xsd

Add rim joists perimeter field

---

schemas/HPXMLDataTypes.xsd

Adds "air-to-water" and "ground-to-water".

Additional heat pump types

---

schemas/BaseElements.xsd

Adds new PV fields for module type, tracking, and system losses.

Additional PV fields

---

schemas/BaseElements.xsd

Adds clothes washer fields for IMEF/IWF, the new EnergyStar performance metrics as of 3/7/15.

Clothes Washer IMEF/IWF

---

schemas/BaseElements.xsd

Adds an `AirInfiltrationMeasurement/InfiltrationVolume` element, needed for calculation of ERI.

Adds InfiltrationVolume element

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Addresses #143.
New | Old
-- | --
attic | attic
attic -   conditioned |  
attic -   unconditioned |  
attic -   unvented |  
attic - vented |  
basement |  
basement - conditioned
basement -   unconditioned | unconditioned basement
crawlspace | crawlspace
crawlspace - conditioned
crawlspace - unconditioned
crawlspace - unvented
crawlspace -   vented |  
garage | garage
garage -   conditioned |  
garage - unconditioned
ground | ground
living space | living space
other | other
other housing   unit | other housing unit
outside | ambient
unconditioned   space |  
New | Old
-- | --
attic |  
attic -   conditioned |  
attic -   unconditioned | unconditioned attic
attic -   unvented |  
attic - vented |  
basement |  
basement -   conditioned |  
basement -   unconditioned | unconditioned …

Standardize Locations

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #180.
(click on the images to make them bigger)

Adding pipe diameter and some other elements to hydronic systems

---

schemas/BaseElements.xsd
schemas/HPXML.xsd
schemas/HPXMLDataTypes.xsd

@nmerket, you can decide when it's the appropriate time to merge this in.

Update HPXML version to 3.0

---

schemas/BaseElements.xsd
schemas/HPXML.xsd
schemas/HPXMLDataTypes.xsd

No functional changes, just makes things more readable.

reformatting and indenting schemas

---

schemas/BaseElements.xsd

Fixes #85 by implementing the changes recommended there.

Fixing project ids

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #96.
`BatteryType` enumerations
- Li-ion
- lead acid
- Ni-Cd
- salt water
- other
`CoolingStrategy` enumerations
- passive
- active air cooling
- liquid cooling

Adding house batteries

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #183 by adding the following at `HPXML/Building/BuildingDetails/Systems/ElectricVehicleChargers`
I'm not an expert on EV charging. What am I missing?

EV Chargers

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Allows duct leakage to be entered as percent of airflow.

Percent duct leakage

---

schemas/HPXMLDataTypes.xsd

Fixes #209 
@juliecaracino as per https://github.com/hpxmlwg/hpxml/issues/209#issuecomment-547040810, I haven't (yet) removed ProgramSponsor. Let me know if I should.

updating BPI-2101 enums in GreenBuildingVerification/Type

---

schemas/BaseElements.xsd

Fixes typo spotted by @lirainer.

Fixes typo.

---

schemas/BaseElements.xsd

Adds a `RadiantBarrierGrade` element for Roofs  (independent from the roof insulation grade).

Radiant Barrier grade

---

schemas/BaseElements.xsd

Adobe wall type

---

schemas/BaseElements.xsd

Adds `Siding` and `Color` elements to RimJoists, for consistency with Walls

RimJoist Siding/Color

---

schemas/BaseElements.xsd

Adds a `Quantity` field for `VentilationFan`. Useful for, e.g., multiple similar bath fans.

Adds VentilationFan/Quantity

---

schemas/BaseElements.xsd

It was presumably an oversight that the `extension` element was missing here.

Adds an extension to the WaterHeating element

---

schemas/HPXMLDataTypes.xsd

Adds IECC years up to 2021. Closes #245.

Update IECC Year choices

---

schemas/BaseElements.xsd

Adds `Location` elements for dishwashers, cooking ranges, and ovens, with the same location choices as the Refrigerator.

Add Location for more appliances

---

schemas/BaseElements.xsd

Adds `Vented` (boolean) and `VentedFlowRate` (double) for ClothesDryers.

Adds clothes dryer venting fields

---

schemas/HPXMLDataTypes.xsd

Adds "conditioned space" to all element types where "living space" is an enumeration. Closes #242.

Adds "conditioned space" enumeration

---

schemas/HPXMLBaseElements.xsd

Remove deprecated `Dehumidifier/Efficiency` field

---

schemas/HPXMLBaseElements.xsd

Add `WaterHeatingSystem/MeasuredTankVolume` element

---

schemas/HPXMLDataTypes.xsd

Remove unused datatypes.

---

schemas/HPXMLBaseElements.xsd

Update `Slab/PerimeterInsulationDepth` documentation.

---

examples/audit.xml
examples/bpi2101.xml
examples/upgrade.xml
schemas/HPXMLBaseElements.xsd

Closes #236.
Renames `NumberofUnits` to `Count`:
- Appliances
- ElectricVehicleCharger
- LightingGroup
Renames `Quantity` to `Count`:
- Door
- Window
- VentilationFan
- WaterFixture
- CeilingFan

Standardize on `Count`

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLDataTypes.xsd

Found while working on https://github.com/hpxmlwg/hpxml/issues/339.

Fix case of CEE enumeration

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Should have been updated as part of https://github.com/hpxmlwg/hpxml/pull/378

Fix RemoteReference documentation

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Adds `IsSharedSystem` and `NumberofUnitsServed` elements for batteries, like exists for PV and many other objects.

Shared batteries

---

examples/upgrade.xml
merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Changes the element from a string to boolean datatype.

Fix `WaterHeaterImprovement/PipeInsulated` element

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds an optional `Building/Site/Elevation` field.

Elevation field

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLDataTypes.xsd

Add Energy Star Cold Climate Heat Pump

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #396.
Needed for HOMES rebates. Keeping it very simple for now. There's a lot of good ideas below. I created a new issue #422 to add those in later.

Electric Panels

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Bowstring Roof

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

adding ClothesDryer/DryingMethod
