hpxmlwg/hpxml

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

This adds the the following element under `Systems/WaterHeating`.
It changes the `Systems/WaterHeating/WaterFixture` to allow it to point to the distribution system. Previously it allowed the fixture to point to the `WaterHeatingSystem`. Now it allows a *choice* of either that or the `HotWaterDistribution`. The ability to select a `WaterHeatingSystem` is required to maintain backwards compatibility.
Speaking of backwards compatibility, the `WaterHeatingSystem` already specified a place to discuss pipe insulation. That was marked as deprecated and the user is recommended to use it in it's appropriate place in `HotWaterDistribution`.
Fixes #31 
@pfairey

Hot water distribution

---

schemas/HPXMLDataTypes.xsd

Adding an enumeration for "indoor water" without a trailing space as part of #74.

WaterType Enum typo fix

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #37 
@brandongallagher 
As discussed in #37, this is technically a breaking change, but provides needed clarification on `AirInfiltrationMeasurement/HousePressure`.
Speak now or forever hold your peace.

Restricting HousePressure to only allow positive values

---

schemas/BaseElements.xsd

Adding `OtherScoreType` and `ScoreDate`. Does this work for everyone?
@brandongallagher @kmwoley @GamalielL @juliecaracino @RebHudson @gmdickey
Fixes #39 
Fixes #40

Energy Score Changes

---

schemas/HPXMLDataTypes.xsd

From David Heslam:
>It would be great if you ask the working group about adding another enumeration for the HES Assessment Type in HPXML called "preconstruction" with a description of "An assessment based on plans for a house under construction".

Adding preconstruction event type

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

This adds a `SolarAbsorptance` and `Emittance` element to [Roof](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/AtticAndRoof/Roofs/Roof) and [Wall](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Walls/Wall). This is needed for both Home Energy Score and Energy Rating Index.
There is a similar pull request that applies this to the attics refactor branch #113. This applies it to v2.3 so we can have it sooner.

Adds solar absorptance and emittance for non-foundation walls/roofs

---

schemas/HPXMLDataTypes.xsd

This adds the enumeration "medium dark" to [Wall/Color](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Walls/Wall/Color) and [Roof/RoofColor](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/AtticAndRoof/Roofs/Roof/RoofColor). It is needed for Home Energy Score. 
Fixes #126

Add 'medium dark' to WallAndRoofColor

---

schemas/HPXMLDataTypes.xsd

Fixes #119 
This adds "2x3" to the list of stud size enumerations. It is used in [Attic/Rafters](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/AtticAndRoof/Attics/Attic/Rafters/Size), [FrameFloor/FloorJoists](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Foundations/Foundation/FrameFloor/FloorJoists/Size), [FrameFloor/FloorTrusses](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Foundations/Foundation/FrameFloor/FloorTrusses/Size), [FoundationWall/InteriorStuds](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclosure/Foundations/Foundation/FoundationWall/InteriorStuds/Size), [RimJoist/FloorJoists](https://hpxml.nrel.gov/datadictionary/2.2.1/Building/BuildingDetails/Enclos …

Add 2x3 stud size enumeration

---

schemas/BaseElements.xsd

Adds an `ExternalResource` element as follows:
The enumerations of `Type` are:
- photo
- illustration
- document
- spreadsheet
- website
- other
It allows 0 to many `ExternalResource` elements in the following places:
- Directly following any `SystemIdentifier` (i.e. on `Wall`, `HeatingEquipment`, etc.)
- `Project/ProjectDetails`
- `Project/ProjectDetails/Measures/Measure`
- `Consumption/ConsumptionDetails/ConsumptionInfo`
- `Building`
Fixes #118

Adding ExternalResource element

---

schemas/BaseElements.xsd

Adds two elements:
Documentation:
> Whether the heat pump backup is integrated into the unit (describe in BackupSystemFuel, BackupAFUE, BackupHeatingCapacity), or a separate heating system (add reference in BackupSystem).
- integrated
- separated
Including an `idref` to point to a `HeatingSystem`.
Documentation:
> References the HeatingSystem that provides the backup for a separate backup.
Fixes #110

Adding heat pump backup reference

---

schemas/BaseElements.xsd

This adds the `FloorFurnace` heating system type with the same subelements as `WallFurnace`.
Fixes #101

Adding FloorFurnace

---

schemas/BaseElements.xsd

Fixes #99 
It now reads:
> This identifies which data quality requirements (if any) were met by the bills for the relevant energy source and therefore which calibration metrics (if any) are used to determine whether the calibrated model is accepted.

Changing docs for BPI2400Inputs/CalibrationQualification

---

schemas/HPXMLDataTypes.xsd

The Weatherization program's choices for "Dwelling Ownership" are "owned", "rented", and "other". This allows "other" to be mapped.

Adds "other" enumeration for Occupancy

---

schemas/HPXMLDataTypes.xsd

Adds "single door with freezer" as a Refrigerator/Type choice. Available choice in the Weatherization program's software interface. All other types already map into HPXML.
For example:
cc @mpathak24

Adds Refrigerator Type choice

---

schemas/BaseElements.xsd

Adds `AutomaticVentDamper`, `PilotLight`, `IntermittentIgnitionDevice`, and `RetentionHead` fields for heating and water heating systems as appropriate:
Element | AutomaticVentDamper | PilotLight | IntermittentIgnitionDevice | RetentionHead
-- | -- | -- | -- | --
Furnace | x | x | x | x
WallFurnace/FloorFurnace | x | x | x | x
Boiler | x | x | x | x
Fireplace | x | x | x |  
Stove | x | x | x |  
WaterHeatingSystem | x | x | x |  
FYI @minimalhotra @mpathak24

Additional heating system properties

---

schemas/BaseElements.xsd

Inputs collected for the Weatherization program. Enumeration choices are borrowed from the existing `Enclosure/AirInfiltration/AirInfiltrationMeasurement/LeakinessDescription` element.
FYI @minimalhotra @mpathak24

Adds LeakinessDescription element to doors/windows/skylights

---

schemas/BaseElements.xsd

For example, heat pumps powered by natural gas exist. This change also makes it easier for software developers to loop through all HVACPlant system types and grab the fuel type.

Adds fuel type element for heat pumps

---

schemas/HPXMLDataTypes.xsd

There's already a generic fuel oil option; now there's a generic coal option for situations where you don't know if it's "anthracite coal" or "bituminous coal".

Adds generic "coal" fuel type

---

schemas/BaseElements.xsd

Expands the number of HPXML elements with these fields.

Add Azimuth/Orientation to RimJoists and FoundationWalls

---

schemas/BaseElements.xsd

Allows specifying the HVAC distribution system a CFIS mechanical ventilation system is attached to. Particularly useful if there is more than one distribution system.

Adds VentilationFan/AttachedToHVACDistributionSystem

---

schemas/BaseElements.xsd

Describes the UnderSlabInsulationWidth element and clarifies its units as ft.

Clarifies UnderSlabInsulationWidth description

---

schemas/BaseElements.xsd

It was missing and I want to use it.

Adds extension element for CeilingFan

---

schemas/BaseElements.xsd

Adds the newer CEF metric for clothes dryers. Also fixes EF to be `EnergyFactor`, not `EfficiencyFactor`.

Clothes Dryer CEF (and EF bugfix)

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds fields to the `WaterFixture` element:
- `LowFlow` (required for ERI)
- `MinutesPerDay` (used by WAP for shower usage; similar to HoursPerDay used by lighting and pool pumps)

Additional WaterFixture fields

---

schemas/BaseElements.xsd

Currently only a single IECC climate zone can be specified in HPXML. This change allows multiple IECC climate zones (for different years) to be specified. 
The ERI calculation requires use of the 2006 IECC climate zone (per 301-2014) and 2012 IECC climate zone (per Addendum E-2018 House Size Index Adjustment Factors).

Multiple IECC climate zones

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Removes any items marked as deprecated in the schema:
- Removes `WaterHeaterInsulation/Pipe`; use `HotWaterDistribution/PipeInsulation` instead.
- Removes `PoolPump/HoursPerDay`; use `PoolPump/PumpSpeed/HoursPerDay` instead.
- Removes comment about `SolarThermalSystem/CollectorLoopType` enumeration that no longer appears relevant.
- Removes "indoor water " (note extra trailing space) enumeration from `WaterType`.
Closes #74.

Deprecates items

---

schemas/BaseElements.xsd

For describing mechanical ventilation energy performance, elements currently include:
- `TotalRecoveryEfficiency` (TRE)
- `SensibleRecoveryEfficiency` (SRE)
This PR adds:
- `AdjustedTotalRecoveryEfficiency` (ATRE)
- `AdjustedSensibleRecoveryEfficiency` (ASRE)
All four elements can be found in the HVI products directory. However, some software tools ask for ATRE/ASRE instead of TRE/SRE. The ATRE/ASRE values exclude the impact of fan energy and, as described by HVI, "should be used for energy modeling when wattage for air movement is separately accounted for in the energy model."

Adds ASRE/ATRE for mechanical ventilation

---

schemas/BaseElements.xsd

`WaterHeatingSystem` elements already support describing a desuperheater, however:
- It's assumed to be attached to a geothermal heat pump
- The `RelatedHeatingSystem` is confusingly named since you would point to a `HeatPump` and not a `HeatingSystem`
This PR adds the flexibility of attaching a desuperheater to an air source heat pump or an air conditioner. While less common, these residential systems exist. The PR allows this by:
- Renaming `HasGeothermalDesuperheater` to `UsesDesuperheater`. Description: "Indicates whether this water heater uses a desuperheater. The attached heat pump or air conditioner can be referenced in the RelatedHVACSystem element."
- Renaming `RelatedHeatingSystem` to `RelatedHVACSystem`. Description: "Reference a HeatingSystem, HeatPump, or CoolingSystem." …

Adds desuperheater flexibility

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

The goal of this change is to allow specifying, e.g.,:
- Interior lighting is 50% LED, 25% CFL, 25% Incandescent
- Exterior lighting is 100% CFL
- Garage lighting is 100% LED
The changes are as follows:
- Adds `FractionofUnitsInLocation` element to `LightingGroup`. Description: "The fraction of lighting units in the specified Location, where all the fractions for the Location sum to 1. If a Location is not specified, fractions apply to the entire building."
- Adds "garage" as a `Location` enumeration choice.
- Allows the same enumeration choices for both `LightingGroup/ThirdPartyCertifications` and `LightingFixture/ThirdPartyCertifications`. Adds "ERI Tier I" and "ERI Tier II" as enumerations choices.
- Removes `LightingFractions` (superseded by this proposal).
Example:
```
<Lighting> …
```

Lighting fraction improvements

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Addresses several inconsistencies as documented in #111. Also fixes #29.
- Renames `HeatPump/AnnualHeatEfficiency` to `HeatPump/AnnualHeatingEfficiency` (now consistent with `HeatingSystem/AnnualHeatingEfficiency`)
- Renames `HeatPump/AnnualCoolEfficiency` to `HeatPump/AnnualCoolingEfficiency` (now consistent with `CoolingSystem/AnnualCoolingEfficiency`)
- Replaces `Measure/InstalledComponent` with `Measure/InstalledComponents/InstalledComponent` (now consistent with `Measure/ReplacedComponents/ReplacedComponent`)
- Renames `FoundationWall/BelowGradeDepth` to `FoundationWall/DepthBelowGrade` (now consistent with `Slab/DepthBelowGrade`)
- Replaces `WeatherStation/SystemIdentifiersInfo` with `WeatherStation/SystemIdentifier` (now consistent with all other elements)
- Renames "central air …

Addresses inconsistencies

---

schemas/HPXMLDataTypes.xsd

Adds "under slab" and 'exterior wall" as choices for `DuctLocation`. These duct locations are found in ASHRAE 152 and many residential software tools.
("roof deck" was added in https://github.com/hpxmlwg/hpxml/pull/156 for similar reasons.)
@GamalielL

New DuctLocation choices

---

schemas/BaseElements.xsd

Adds new `TankWall` insulation element with fields:
- `TankWallRValue`, `InsulationMaterial`, and `Thickness`
These fields are collected as part of DOE's Weatherization program.
For consistency, also adds fields for `Jacket` insulation:
- `InsulationMaterial` and `Thickness`

Adds WaterHeaterInsulation fields

---

schemas/BaseElements.xsd

For windows/skylights, splits `InteriorShadingFraction` into `InteriorShadingFractionSummer` and `InteriorShadingFractionWinter`. Many software tools and standards use two different numbers.

Window/Skylight Interior Shading Fraction

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Addresses #125. Adds "continuous - interior" and "continuous - exterior" to `InstallationType` element, which can be defined for each insulation `Layer`. Removes `InsulationLocation` element. 
This new approach makes it clear that the interior vs exterior insulation location is meant to only apply to continuous insulation layers. The "continuous" option is still allowed if the insulation location is unknown.

Allow insulation location to be layer-specific

---

schemas/BaseElements.xsd

Documents that `InsulationMaterial/None` implies insulation not present and `InsulationMaterial/Unknown` implies insulation present (but material type unknown).
Also adds a `DuctInsulationMaterial` to allow similar characterization for ducts.

Presence of Insulation

---

schemas/BaseElements.xsd

Similar to `Window.Area`, the documentation now clarifies that `Door.Area` should take into account the `Quantity` of doors.

Door area documentation

---

schemas/BaseElements.xsd

Fixes #170 
Adds a list of homeowner concerns as `/HPXML/Customer/HomeownerConcerns`
This would look something like
```xml
<Customer>
<CustomerDetails>
<Person>
<SystemIdentifier id="homeowner"/>
<Name>Joe Homeowner</Name>
</Person>
</CustomerDetails>
<Comments>
<Comment>ice damming</Comment>
<Comment>neighbor's dog poops on my lawn</Comment>
<Comment>thermal comfort</Comment>
<Comment>keeping up with Jonses</Comment>
</Comments>
</Customer>
```
~~I'm not 100% sure this is the best way to do this, so I'd like to have some discussion about it. Maybe this should be called `CustomerConcerns`?~~
Changed to `Comments/Comment` to make more general.
@Tedkidd

Adding customer comments element

---

schemas/BaseElements.xsd

Adds rated performance values for SolarThermalSystems based on SRCC. 
For solar thermal collector ratings (OG-100):
- `CollectorRatedOpticalEfficiency`: Often referred to as Fr-tau-alpha (FRta), this describes the optical efficiency portion of the overall collector efficiency. In the OG-100 SRCC Certified Solar Thermal Collector Directory, this is the y-intercept of the efficiency curve.
- `CollectorRatedThermalLosses`: Often referred to as Fr-Ul (FRUl), this describes the collector thermal losses portion of the overall collector efficiency. In the OG-100 SRCC Certified Solar Thermal Collector Directory, this is the slope of the efficiency curve.
For solar water heating system ratings (OG-300):
- `SolarFraction`: The Solar Fraction is the portion of the total conventional hot water …

Adds SolarThermalSystem performance elements

---

schemas/HPXMLDataTypes.xsd

Adds "other housing unit above" and "other housing unit below" enumerations for `AdjacentTo`. The "other housing unit" enumeration is still available.
Usually you can infer whether a `FrameFloor` is actually a ceiling or floor surface. For example: 
- A `FrameFloor` with InteriorAdjacentTo="living space" and ExteriorAdjacentTo="attic - vented" is clearly a ceiling below the attic 
- A `FrameFloor` with InteriorAdjacentTo="living space" and ExteriorAdjacentTo="basement - unconditioned" is clearly a floor above a basement
But if you have a `FrameFloor` with InteriorAdjacentTo="living space" and ExteriorAdjacentTo="other housing unit" it is impossible to infer. With this change, you can clarify the ExteriorAdjacentTo as either "other housing unit above" (i.e., ceiling) or "other housing unit …

Additional AdjacentTo enumerations

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #172.
Add the following element under `Building/BuildingDetails/Systems/WaterHeating`.
It also adds a boolean element `HasMixingValve` to `WaterHeatingSystem`.

DHW Controllers

---

schemas/BaseElements.xsd

Clarifies that `InverterEfficiency` needs to be 0-1 (fraction), not 0-100 (percentage). I guess this is technically a breaking change if someone was using the percentage convention?

Clarify PV inverter efficiency value

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #12.
Moving a bunch of window features into separate sub components with their own ids.
Questions:
- `MoveableInsulation/Material` uses the [same list](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Walls/Wall/Insulation/Layer/InsulationMaterial) that's in any other insulation element. Is that appropriate here?
- Should `Overhangs` be connected to or under `ExteriorShading`?
- Should interior shading be similarly described?
- Did I miss anything?

Window sub-components

---

schemas/BaseElements.xsd
schemas/HPXML.xsd
schemas/HPXMLDataTypes.xsd

This adds a `dataSource` attribute with the following enumerations
- user
- software
- ~~software default~~
- ~~imputed~~
The next big question we need to answer is _which_ elements need this attribute? Some examples to stir up discussion:
- Orientation / Azimuth 👍 
- WalkingScore 👎 
- NumberofAdults / NumberofChildren 🤷‍♂ 
- Occupancy (owner vs renter) 🤷‍♂ 
- FoundationType 👎 
- VentilationRate 👍 
- WallType 🤷‍♂ 
- Wall/Area 👍 
- Wall/Color 👀 ❓ 
- FloorJoists/Size 👀 
- FloorJoists/Spacing 👍 
- Insulation/InsulationGrade 👍
- HVAC system types 👎  (should be observable, right?)
And there's more. It's going to be pretty disruptive to put these on _everything_. Almost every line of the schema will change.

Adding dataSource attribute

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds `Wall/WallType/WoodStud/FramingType` field with choices:
- platform
- balloon
- timber
Here is a good article explaining the differences: https://thecraftsmanblog.com/framing-timber-balloon-platform/

Adds wood stud wall framing type field

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds a `StormWindow/GlazingMaterial` element to characterize, e.g., plastic (instead of glass) storms. Options are:
- glass
- plastic
- other

Adds storm window material field

---

schemas/BaseElements.xsd

I don't know what happened to said wiki, but it clearly doesn't exist anymore. There was only a single reference to it, though.

Removes outdated reference to HPXML wiki

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Changes `AssemblyEffectiveRValue` from minInclusive=0 to minExclusive=0. The R-values associated with insulation materials are unchanged (i.e., they can still be zero).
An assembly effective R-value, which is documented as including air films, can never be zero. This change is proposed to prevent software tools from potentially _incorrectly_ using a value of zero. This change helps to ensure that all software tools consistently include air films in their value.

Requires AssemblyEffectiveRValue to be > 0

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds `PerformanceClass` element for windows, skylights, and doors per AAMA Standard. Choices are:
- residential
- architectural
- light commercial
- commercial
- heavy commercial

Adds PerformanceClass element for fenestration

---

schemas/BaseElements.xsd

Forces `AnnualHeatingDistributionSystemEfficiency` and `AnnualCoolingDistributionSystemEfficiency` values to be fractions (0-1). The schema currently allows any number to be provided, so a software tool could be using percentages (0-100). Updated documentation.

DSE values as fractions

---

schemas/BaseElements.xsd

Documents that the `PerformanceAdjustment` elements for HVAC and water heaters should be entered as a multiplier (instead of, e.g., an adder).

PerformanceAdjustment clarification

---

schemas/BaseElements.xsd

Adds Energy Guide Label fields for Dishwashers; uses the same names that ClothesWashers use.
- `LabelElectricRate`
- `LabelGasRate`
- `LabelAnnualGasCost`
Also adds `LabelUsage` to both Dishwashers and ClothesWashers, to make a distinction between the cycles/week used in the label/rating and the cycles/week of actual operation (`Usage`).

Adds Dishwasher/ClothesWasher label fields

---

schemas/BaseElements.xsd

Documents that the units for `SolarThermalSystem/CollectorRatedOpticalEfficiency` should be Btu/h-ft^2-F.

Adds units to CollectorRatedOpticalEfficiency

---

schemas/BaseElements.xsd

Adds a `StandbyLoss` field to capture an indirect water heater's standby loss, per the AHRI Directory.

Indirect water heater standby loss

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds `WaterHeatingSystem/UsageBin` element with enumerations ("very small", "low", "medium", or "high"). This input could be provided instead of the numeric First Hour Rating.
Both the usage bin and the FHR are available on a water heater's label (for water heaters that are rated w/ a Uniform Energy Factor).

Adds UsageBin element for water heaters

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Allows describing the interior finish for Walls, FoundationWalls, FrameFloors (e.g., ceilings), and Roofs (e.g., cathedral ceilings).
Type choices:
- gypsum board
- gypsum composite board
- plaster
- wood
- other
- none
Color choices are the same as other similar elements in HPXML (i.e., light, medium, medium dark, dark, reflective).

Adds InteriorFinish element for enclosure surfaces

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds a `StormWindow/Location` element with choices of "interior" and "exterior". Closes https://github.com/hpxmlwg/hpxml/issues/266.

Add Location for storm windows

---

schemas/HPXMLDataTypes.xsd

Adds "none" as a choice for the `Siding` element. (This is different from omitting the `Siding` element, which might indicate that the siding type is unknown rather than not present.)

Adds "none" as a siding type

---

schemas/BaseElements.xsd
schemas/HPXMLDataTypes.xsd

Many cities, such as NYC, mandate lengths of heating seasons in rental properties. For NYC, it is from October 1 to May 31st (regardless of weather conditions).
On `BuildingDetails/Systems/HVAC/HVACControl`:
`Month_simple` is restricted to integers 1 - 12, and `DayOfMonth_simple` is restricted to integers 1 - 31.

HeatingSeason and CoolingSeason

---

schemas/BaseElements.xsd

For furnaces, [AHRI ratings](https://www.ahridirectory.org/NewSearch?programId=64&searchTypeId=3) include "Input Rating" and "Output Heating Capacity".
Most auditors probably collect input heating capacities. Most BEM tools probably collect output heating capacities. Though HPXML did define `HeatingCapacity` as _input_ heating capacity, it's likely that it was being used inconsistently for different use cases, since there was only a single element available.
To align with AHRI, this PR proposes to:
- Add `HeatingSystem/HeatingInputRating` (and `HeatPump/BackupHeatingInputRating`) elements
- Change the definition of `HeatingSystem/HeatingCapacity`  from _input_ heating capacity to _output_ heating capacity
- Clarify that all `CoolingCapacity` and `HeatPump/HeatingCapacity` and …

Address input vs output heating capacities

---

schemas/BaseElements.xsd

Adds an `AirInfiltrationMeasurement/InfiltrationHeight` element, alongside the existing `InfiltrationVolume` element. It is defined as: "[ft] Vertical distance between lowest and highest above-grade points within the pressure boundary, per ASHRAE 62.2."

Infiltration Height

---

schemas/HPXMLDataTypes.xsd

Adds "concrete block perlite core" and "concrete block solid core" as enumerations for `FoundationWall/Type`, based on Table 2 of https://ncma.org/resource/rvalues-ufactors-of-single-wythe-concrete-masonry-walls/.

Add `FoundationWall/Type` enumerations

---

schemas/HPXMLDataTypes.xsd

Closes #287. Adds:
- `GlassLayers`: "glass block"
- `GasFill`: "krypton", "xenon", "nitrogen"
- `GlassType`: "clear"

Adds more window property choices

---

schemas/HPXMLBaseElements.xsd

New elements for a HeatPump:
- `CompressorLockoutTemperature`: "[deg F] Temperature below which the compressor is disabled, often to prevent damage or occupant comfort issues. The default is the manufacturer's minimum operating temperature, but the value may be set higher. For a duel-fuel heat pump, use the BackupHeatingSwitchoverTemperature element."
- `BackupHeatingLockoutTemperature`: "[deg F] Temperature above which the backup heating is disabled, often to prevent backup heating usage during recovery from a thermostat heating setback. For a duel-fuel heat pump, use the BackupHeatingSwitchoverTemperature element."
Also adds documentation to the `BackupHeatingSwitchoverTemperature element`: "[deg F] Temperature at which the backup heating is activated _and the compressor is disabled in, …

Add HeatPump lockout temperature elements

---

schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

- Adds `GeoLocation` element, with `Latitude`, `Longitude`, `PlusCode`, `UBID`, and `extension` children
- Adds "Puerto Rico" as an additional `eGridRegion` enumeration choice
- Adds `eGridSubregion` element
- Adds `CambiumRegionGEA` element (closes #300)
- Adds `TimeZone` element, with `Name`, `Abbreviation`, `UTCOffset`, `DSTObserved`, and `extension` children

Expand `Building/Site`

---

schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Changes the `Efficiency` datatype from `minInclusive=0` to `minExclusive=0`, which will help prevent inappropriate values (whether a bad user input or a software bug). It's hard to imagine how anything could have an efficiency of zero, as that would apply it consumes energy but produces nothing of value.
Also changes `CeilingFan/Efficiency` from an `HPXMLDouble` datatype to the `Efficiency` datatype.
Is this considered a breaking change?

Disallow zero for efficiencies

---

schemas/HPXMLDataTypes.xsd

Adds "SEER2" and "EER2" to `CoolingEfficiencyUnits` and "HSPF2" to `HeatingEfficiencyUnits`. Effective Jan 1, 2023. Closes #325.

Adds SEER2, EER2, and HSPF2

---

schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Closes #333. 
**Conventional storage and instantaneous commercial water heaters**
- Replaces `StandbyLoss` with `StandbyLoss[Units]/Value` to support different units (F/hr, %/hr, or Btu/hr). This is a breaking change.
- Already has a `ThermalEfficiency` element.
**Heat pump commercial water heaters**
- Adds a `HeatPumpCOP` element.

Support commercial water heaters

---

schemas/HPXMLBaseElements.xsd

Remove "Loop" from `Recirculation/BranchPipingLoopLength` name

---

schemas/HPXMLDataTypes.xsd

Closes #329. Adds "low-e, high-solar-gain" and "low-e, low-solar-gain" as `GlassType` enumerations for windows and skylights.

Additional `GlassType` low-e enumerations

---

examples/audit.xml
examples/bpi2101.xml
examples/upgrade.xml
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Fixes #321 
Renames `FrameFloors/FrameFloor` to `Floors/Floor`.
Renames `WallType/StructurallyInsulatedPanel` to `WallType/StructuralInsulatedPanel`
Adds `FloorType` with choices of:
- `WoodFrame`
- `StructuralInsulatedPanel`
- `SteelFrame`
- `SolidConcrete`
- `Other`

Allow additional floor types

---

schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Closes #330.
Adds a new CFISControls element under `VentilationFan:
- `CFISControls` (Relevant when FanType="central fan integrated supply".)
- `HasOutdoorAirControl`: boolean (Has controls to block the flow of outside air when the CFIS system is not ventilating. For example, an electronically-controlled mechanical damper, or an in-line fan that substantially blocks the flow when not running.)
- `AdditionalRuntimeOperatingMode`: "none", "air handler fan", "supplemental fan", or "other" (Describes if/how the CFIS system provides additional ventilation beyond when the HVAC system is running to meet a given ventilation target.)
- `SupplementalFan`: idref` (When AdditionalRuntimeOperatingMode="supplemental fan", specifies the VentilationFan that serves as that supplemental fan.)
- `extension`

New `CFISControls`

---

examples/audit.xml
examples/bpi2101.xml
examples/upgrade.xml
schemas/HPXMLBaseElements.xsd

Facilitates referring to specific ducts for, e.g., upgrade measures.

Adds a `SystemIdentifier` element for Ducts

---

schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Closes #253. Adds `Floor/FloorOrCeiling`: string (choices: "floor", "ceiling"). From the perspective of the living/conditioned space. Often it can be inferred from other information in the HPXML, but not always. This is particularly useful because a lot of standards (like IECC, ANSI 301, etc.) refer to ceilings and floors.
(I'm not calling it `FloorType` because that is being used [here](https://github.com/hpxmlwg/hpxml/pull/332) to support wood frame floors vs mass floors vs ...).
This is a far simpler implementation than [adding an `Enclosure/Ceilings` element](https://github.com/hpxmlwg/hpxml/pull/264), which would require a lot of software updates. 
Should we also deprecate (or mark as deprecated) the "other housing unit above" and "other housing unit below" AdjacentTo enumerations? …

Adds `FrameFloor/FloorOrCeiling` element

---

schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Closes #294. Moves inverter field into a new `Inverter` element, on the same level as the `PVSystem` element. One or more `PVSystem`s can optionally reference an inverter via a new `AttachedToInverter` element.
Also adds a new `InverterType` element (based on https://powmr.com/blog/types-of-pv-inverters/) with choices of:
- central inverter
- string inverter
- multi-string inverter
- micro inverter
- other

Standalone `Inverter`

---

schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds "split heat pump water heater" choice to `WaterHeaterType`. Adds documentation to `WaterHeaterType`: The generic "heat pump water heater" enumeration is assumed to refer to an integrated (not split) heat pump water heater.
New `HPWHOperatingMode` element with choices of:
- hybrid/auto
- heat pump only
- electric heater only
- high demand/recovery
- other
Closes #313.
Allows/documents how to separately describe the heat pump capacity and the electric resistance capacity for a heat pump water heater.
- Existing `HeatingCapacity` element: [Btuh] For a heat pump water heater, the capacity of the heat pump.
- New `BackupHeatingCapacity` element: [Btuh] The capacity of the electric resistance heating in a heat pump water heater.

Additional HPWH inputs

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Can accommodate, e.g., cold climate heat pump performance data from the [NEEP database](https://ashp.neep.org) or expanded manufacturer's data.
New schema element proposed under `HeatPump` for heating (similar for cooling):
Example product from NEEP:
Example HPXML snippet for this product:
```xml
<HeatPump>
<SystemIdentifier id='HeatPump1'/>
<DistributionSystem idref='HVACDistribution1'/>
<HeatPumpType>mini-split</HeatPumpType>
<HeatPumpFuel>electricity</HeatPumpFuel>
<HeatingCapacity>16000.0</HeatingCapacity>
<CoolingCapacity>12000.0</CoolingCapacity>
<AnnualCoolingEfficiency>
<Units>SEER</Units>
<Value>21.3</Value>
</AnnualCoolingEfficiency>
<AnnualHeatingEfficiency>
<Units>HSPF</Units>
<Value>11.7</Value>
</AnnualHeatingEfficiency>
...
<CoolingDetailedPerformanceData> …
```

Heat pump detailed performance inputs

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Current definition:
> This should indicate the effective R-value of the complete assembly including any air films or other treatments.
Proposed definition:
> This should indicate the effective R-value of the complete assembly including any air films or other treatments. **For below-grade surfaces adjacent to ground, it should not include the insulating effect of the ground.**
Closes #358.

Clarify `Insulation/AssemblyEffectiveRValue` for surfaces adjacent to ground

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Found some HPXML files produced by a software tool in which the ventilation fans were described as ERVs with TotalRecoveryEfficiency=0. This doesn't make sense; either TRE needs to be greater than zero or it's actually an HRV.
I looked through all the HPXML elements like these that are of type `Fraction` and propose changing a few of them to use a minimum value of zero _exclusive_ instead of zero _inclusive_:
- VentilationFan/TotalRecoveryEfficiency
- VentilationFan/SensibleRecoveryEfficiency
- VentilationFan/AdjustedTotalRecoveryEfficiency
- VentilationFan/AdjustedSensibleRecoveryEfficiency
- HVACDistribution/AnnualHeatingDistributionSystemEfficiency
- HVACDistribution/AnnualCoolingDistributionSystemEfficiency
- DrainWaterHeatRecovery/Efficiency
- Inverter/InverterEfficiency
- …

Disallow zero for some elements

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds a `BuildingSummary/Site/Soil` element as follows:
SoilType choices:
- sand
- silt
- clay
- loam
- gravel
- other
- unknown
MoistureType choices:
- wet
- dry
- mixed

Soil properties

---

README.rst
guide/source/index.rst
guide/source/overview.rst
guide/source/program_administrator/program_management_systems.rst
guide/source/software_developer/introduction.rst
guide/source/standard_datasets.rst
guide/source/tools_and_resources.rst

First, thanks for supporting these fantastic tools!
When perusing documentation I noticed a broken link in the README. 
`http://hpxmlonline.com` is broken because the server is set to reject non-HTTPS requests instead of redirecting them. 
So, a user clicking this link in the readme will, for most browsers, wait 30 seconds and then receive a time out error.
The best way to fix this is to add logic to your webserver to redirect non-secure requests to HTTPS, but changing the links is also useful. 
Note that I have not changed any of the non-secure links in the XML namespace (e.g. `<HPXML xmlns="https://hpxmlonline.com/2019/10"  schemaVersion="3.1">` because these uses are just namespaces, not actual resolveable URLs, and are sensitive to the protocol (e.g. `http` vs `https`) …

Fix broken link in README

---

examples/audit.xml
examples/bpi2101.xml
examples/invalid.xml
examples/upgrade.xml
schemas/HPXMLBaseElements.xsd

Changes the `RemoteReference` base element so that the "id" attribute (of type xs:idref) is now an "idref" attribute.
Closes #284.

Fix idref attribute

---

examples/audit.xml
examples/invalid.xml
examples/upgrade.xml
schemas/HPXMLBaseElements.xsd

Previously:
`HealthAndSafety/CombustionAppliances/CombustionApplianceZone/CombustionApplianceTest/CarbonMonoxideTest/MaxAmbientCOinLivingSpaceDuringAudit`
Now:
`HealthAndSafety/CombustionAppliances/MaxAmbientCOinLivingSpaceDuringAudit`
Closes #87.

Move `MaxAmbientCOinLivingSpaceDuringAudit` element

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Adds a `LightingGroup/Load` element, similar to the `PlugLoad/Load` element. Allows specifying the lighting usage in kWh/yr or W. (There is an existing `LightingGroup/AverageWattage` element, but it's W **per unit** and thus requires the number of units, which may not be known/collected, to obtain the total wattage.)
E.g.:
```xml
<LightingGroup>
<SystemIdentifier id='LightingGroup'/>
<Location>interior</Location>
<Load>
<Units>kWh/year</Units>
<Value>620</Value>
</Load>
</LightingGroup>
```

Add `LightingGroup/Load` element

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

There is currently no way to know what an air infiltration measurement value for a multifamily dwelling unit represents. I propose adding an `AirInfiltrationMeasurement/TypeOfInfiltrationLeakage` element with choices of:
- building total
- unit total
- unit exterior only
- unit interior only
The element is documented as:
> This element is intended to describe the type of infiltration measured, e.g., for an individual single-family attached or multifamily dwelling unit. Either whole building or single unit infiltration can be measured. For single unit infiltration, leakage can occur through exterior surfaces, interior surfaces, or both. For example, guarded tests measure unit exterior leakage, unguarded or compartmentalization tests measure unit total leakage, and combining both tests can …

Infiltration for multifamily buildings

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Adds:
- `IsSharedSystem` for HVAC systems (e.g., to describe a central boilers)
- `IsSharedSystem` for water heating systems (e.g., to describe central water heaters serving multiple dwelling units or a shared laundry room)
- `IsSharedSystem` for ventilation fans  (e.g., to describe shared mech vent system serving multiple dwelling units )
- `IsSharedSystem` for PV (e.g., to describe a PV system serving the entire MF building)
- `IsSharedAppliance` for appliances (e.g., to describe appliances in a shared laundry room)
Also adds a `NumberofUnitsServed` alongside each of these.

Add elements for shared systems/appliances

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

New `DuctBuriedInsulationLevel` element with choices of:
- not buried
- partially buried
- fully buried
- deeply buried
Description of element: "Describes ducts buried in, e.g., attic loose-fill insulation. Partially buried ducts have insulation that does not cover the top of the ducts. Fully buried ducts have insulation that just covers the top of the ducts. Deeply buried ducts have insulation that continues above the top of the ducts. See https://basc.pnnl.gov/resource-guides/ducts-buried-attic-insulation for more information."
Also:
- Updates `DuctInsulationRValue` description: "This should exclude the exterior air film -- e.g., use zero for uninsulated ducts. For ducts buried in insulation, this should only represent any surrounding insulation duct wrap and not the entire attic …

Buried ducts

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Closes #363.
Choices are the same as what's used for surface `AdjacentTo` elements:
attic
attic - conditioned
attic - unconditioned
attic - unvented
attic - vented
basement
basement - conditioned
basement - unconditioned
conditioned space
crawlspace
crawlspace - conditioned
crawlspace - unconditioned
crawlspace - unvented
crawlspace - vented
garage
garage - conditioned
garage - unconditioned
ground
living space
other
other housing unit
other housing unit above
other housing unit below
outside
unconditioned space

HPWH ducting elements

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Adds a `Walkout` boolean element for the basement foundation type.

Add Walkout basement element

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

See #289
Adds `BellyAndWing` foundation type to support mobile homes.
> The floor is supported on a pair of I-beams spanning across the length of the manufactured home. The floor wing is the part of the floor outside the supports, and the floor belly is the part between the supports. The floor wing and belly sections are protected from outside elements including water, wind, and rodents using a wrap attached to the underside of floor joists, and may contain insulation. ~~Use separate Floor elements to describe the floor insulation above the belly and wing sections respsectively.~~
- good
- fair
- poor
- none
> Use the 'none' choice for cases where the belly wrap is functionally missing even if pieces of the wrap are still present.

Add BellyAndWing foundation type and ManufacturedHomeSections

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Makes `PlugLoad/Location` and `FuelLoad/Location` elements consistent with `LightingGroup/Location`.
This means that the plug/fuel load location choices expand from:
- interior
- exterior
to:
- interior
- exterior
- garage
- common area
So now you can describe plug/fuel loads in garages and common areas.

Add `PlugLoad/Location` and `FuelLoad/Location` choices

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds a `Ducts/DuctShape` element with choices of:
- rectangular
- round
- oval
- other
As duct insulation R-values get higher, effective duct R-values (incorporating air film and [insulation derating for round ducts](https://www.eceee.org/static/media/uploads/site-2/library/conference_proceedings/ACEEE_buildings/2006/Panel_1/p1_18/paper.pdf)) diverge between round and rectangular ducts.

New `DuctShape` element

---

merged_schema/HPXMLMerged.xsd
schemas/HPXML.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Adds `RadiantBarrier` and `RadiantBarrierGrade` for HPXML Wall/Floor elements, which can be used for attic gable walls and attic floors. Removes "attic floor" as a choice from `Roof/RadiantBarrierLocation`.

Allow radiant barriers for (attic) walls/floors

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Related to #229.
Based on feedback from Jennifer Hatfield with PHTA:
- Changes the datatype for `TotalAnnualPowerConsumptionInStandbyMode` to be `RatedAnnualkWh`, which is accurately just a single number. The previous data type selection was an error.
- Removes `FilterType` from `PortableElectricSpa` because they all use cartridge filters, so there is no good reason to ask for something that will likely lead to an erroneous input.

Portable Electric Spa Fixes

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Require values > 0 for various appliance elements (e.g., `Capacity`, `EnergyFactor`, `LabelElectricRate`) to prevent bad inputs from some software tools. Some appliance elements already have the restriction.

Appliance minimum values

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Adds four `CeilingFan/LabelFoo` elements for the current EnergyGuide label. Here's an [example](https://hubbellcdn.com/EnergyGuide/PROG_FTC-label-P2501_energyguide.pdf).

Additional `CeilingFan` elements

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

See [here](https://framebuildingnews.com/below-grade-insulation-part-1/) and [here](https://www.renovation-headquarters.com/foundations-29.html) for examples. Sometimes also referred to as "wing" or "skirt" insulation.
Very similar to the existing `PerimeterInsulation` and `UnderSlabInsulation` elements.

Adds a `Slab/ExteriorHorizontalInsulation` element

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Bugfix for https://github.com/hpxmlwg/hpxml/pull/406. The description was previously updated to allow negative values, but I forgot to update the datatype.

Allow `UnitHeightAboveGrade` to be negative

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Additional elements for the new `Window/InsectScreen`:
1. Adds `SummerShadingCoefficient` and `WinterShadingCoefficient` fields, now consistent with `InteriorShading`/`ExteriorShading`.
2. Adds `ScreenMaterial` with options of: "fiberglass", "aluminum", "polyester", "stainless steel", "bronze copper", and "other".

Window insect screens, part 2

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd
schemas/HPXMLDataTypes.xsd

Closes #404. Adds elements to `WaterHeatingSystem`:
`HPWHVoltage`: Enumeration with choices of: "240V", "120V", "120V, dedicated circuit", "120V, shared circuit", and "other". 
`MixingValueSetpoint`: Temperature > 0.

HPWH additional fields

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Previously only allowed one location, most likely inadvertently. Now you can specify e.g. home=50%, work=25%, public=25%.

Allow multiple `FractionChargedLocation` for an EV

---

merged_schema/HPXMLMerged.xsd
schemas/HPXMLBaseElements.xsd

Replaces #399.
Updates the documentation for the `sameas` attribute in a couple ways:
1. In an upgrade use case, makes it clear that the `sameas` attribute should only be used *when the building component has not changed*. This is consistent with the HPXML Implementation Guide as described [here](https://hpxml-guide.readthedocs.io/en/latest/software_developer/references.html#sameas) and [here](https://hpxml-guide.readthedocs.io/en/latest/software_developer/usecases/auditupgrade.html#post-upgrade).
2. In an upgrade use case where the building component *has* changed, makes it clear that a `Measure` should be used to link the components instead. (Indeed, this is the only way to handle an AC/furnace -> HP retrofit.)
3. Expands the description to allow the `sameas` attribute to be used for …

Clarify `sameas` attribute
